# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26a65c62016c3529dac434d93bff40cb108c376477b00e9d653f15ff42aac122de1a2b2c71439138b111ec4a5c25ea098226d53c0a38ce24296bcee05addd00

test:
  secret_key_base: 7f32af966e17555dbd46ebe5c21e44f5a77153201cc35417c565b1983a1d9d32a73af5d72ba16ab80bfa64f79549990638407ad752a36991daa1bf4ff198c8c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
